package process2
import java.util.Calendar;
import java.util.Date;
import com.example.droolsdemo.Demo1.entity.PersonFact;

rule "age-rule"
	ruleflow-group "age-check-group"
    lock-on-active true
    when
        p:PersonFact()
    then
        System.out.println("hello"+p.getName());
        if(p.getBirthday()!=null){
    		int age =0;
    		Calendar now = Calendar.getInstance();
            now.setTime(new Date());

            Calendar birth = Calendar.getInstance();
            birth.setTime(p.getBirthday());

            if (birth.after(now)) {
                age = 0;
            } else {
                age = now.get(Calendar.YEAR) - birth.get(Calendar.YEAR);
                if (now.get(Calendar.DAY_OF_YEAR) > birth.get(Calendar.DAY_OF_YEAR)) {
                    age += 1;
                }
            }

            p.setAge(age);
    	}

end

rule "teenager-rule"
	ruleflow-group "teenager"
    lock-on-active true
    when
        p:PersonFact()
    then
        System.out.println(p.getName()+"是一名青少年");
end

rule "adult-rule"
	ruleflow-group "adult"
    lock-on-active true
    when
        p:PersonFact()
    then
        System.out.println(p.getName()+"是一名成年");
end
